package(default_visibility = ["//visibility:public"])

config_setting(
    name = "wasm_build",
    constraint_values = ["@@platforms//os:emscripten"],
)

config_setting(
    name = "macos_build",
    constraint_values = ["@@platforms//os:macos"],
)
